# 服务
server:
  port: 8008

# springboot 配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.9:5432/devdb
    username: postgres
    password: 20191809
